### ISSUE TITLE
example

### ISSUE THREAD

**Issue by Juris3D** [ldmfield/RebindableKeys#1]
Hello. Could it be possible to have simple BP example with all plugin's BP nodes used as intended? Thank You.

**Comment by ldmfield** [comment]
Yes it is possible! I've made a note of your request and should be able to get to it over the weekend!

**Comment by Juris3D** [comment]
Awesome. I will wait eagerly. I am still a UE beginner (1 year of little free hours), not "feeling" everything yet. Made the same question on your youtube, sorry for double.

**Comment by Juris3D** [comment]
I partially figured out something, but example from Author really would be nice. Some functionality is still confusing to me :) Thank you.

**Comment by ldmfield** [comment]
Thanks for your continued interest, I have a sample ready and will try to find sometime to upload it in some form tomorrow.

**Comment by ldmfield** [comment]
![image1](https://user-images.githubusercontent.com/2104577/51804155-0dc3a180-2255-11e9-9f3e-73542e574b26.PNG)
![image2](https://user-images.githubusercontent.com/2104577/51804156-0dc3a180-2255-11e9-8d9e-724f2172750f.PNG)
![image3](https://user-images.githubusercontent.com/2104577/51804157-0dc3a180-2255-11e9-98eb-b850981bf939.PNG)
![image4](https://user-images.githubusercontent.com/2104577/51804158-0dc3a180-2255-11e9-908e-bcf214b33172.PNG)

**Comment by Juris3D** [comment]
Thank You! Appreciated.
